toolbar_check_activated(button_select_all_options);
toolbar_check_activated(button_preset_S);
toolbar_check_activated(button_preset_L);
toolbar_check_activated(button_optifine_toggle);
toolbar_check_activated(button_optifine_download);
toolbar_check_activated(button_create_RP);
toolbar_check_activated(button_create_zip);

toolbar_update_button(button_optifine_toggle);
